export const LOGOUT = "LOGOUT";
export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT'

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS'
export const GET_CONTACTS_ATTEMPT = 'GET_CONTACTS_ATTEMPT'